### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Garridan** [Null-MC/Shrimple#14]
The shaders fail to compile and the game crashes, that's all the information I have on the issue.
I'm using iris 1.6.2 and sodium 0.4.4. I have an i5-9400f processor, 32GB DDR4, and an AMD Saphire Nitro RX 5700XT with 8GB Video memory

**Comment by null511** [comment]
Nobody else has reported this issue, and without any kind of log about what went wrong there's not much I can diagnose.

**Comment by Garridan** [comment]
> Nobody else has reported this issue, and without any kind of log about what went wrong there's not much I can diagnose.

[crash-2023-05-08_17.53.43-client.txt](https://github.com/Null-MC/Shrimple/files/11468619/crash-2023-05-08_17.53.43-client.txt)

**Comment by null511** [comment]
ah
> Shader compilation failed, see log for details

I need your latest error log; crash report doesn't tell me any more than this. Since I can see your on AMD though, I'm assuming your using the latest _release_ [0.8] which the newest AMD drivers break support for.

Good news is I already worked around that, grab the latest "code download" from here instead of release and it should work fine.
