### ISSUE TITLE
[Enhancement] add option to disable torch colour flikering

### ISSUE THREAD

**Issue by hl2jeep** [Null-MC/Shrimple#43]
hi, i love this shader and it works well for me, however one annoying thing is when im using a torch in my offhand it constantly changes light temperature, it gets very annoying after a while, please add an option to disable it, maybe also options for controling light colour tempuratures.

**Comment by null511** [comment]
That's already an option:
 - [Lighting] > `Torch/Fire Temp`: controls the base color-temp in kelvin.
 - [Lighting] > [Trace Options] > `Dynamic`: Turns flickering on/off
 
 If you don't see those options, grab the latest in-dev version by using the "Download as Code" option in github (rather than releases)
