### ISSUE TITLE
(Suggestion) Add RGB Block light setting...

### ISSUE THREAD

**Issue by TwinShards** [Null-MC/Shrimple#46]
-Add RGB/Brightness setting for each blocks emitting light.

-Add Texture brightness option for blocks with bright texture like nether wood's veins for example.

List of blocks (wich could be emitting light with shader)/with bright texture i have in mind:

-RedStone: Detector/Powered/Activator Rail, Observer
-All Sculk blocks
-Glow Berry Vines(without berries)
-Crimson/Warped Stem/Hyphae
-Ender Dragon Egg

All ores:
-Gilded BlackStone
-Quartz Ore
-(Nether) Gold Ore
-Iron Ore
-Copper Ore
-RedStone Ore/Block
-Emerald Ore/Block
-Diamond Ore/Block
-Lapis Ore/Block
-Amethyst; Block, Budding,

**Also, Fog Option to reduce/remove fog in water/lava and in the nether**

**Comment by null511** [comment]
> Add RGB/Brightness setting for each blocks emitting light.

I most likely won't be adding this unless Iris adds a color-picker control for shaders, as having a thousand separate RGB sliders would suck to both maintain, and use.

> Add Texture brightness option for blocks with bright texture like nether wood's veins for example.

The apparent brightness (not light casted onto other objects) is controlled by the resource pack emission; you want to use an OldPBR or (preferably) LabPBR enabled pack. You can adjust the overall range/max value of emission in Material settings.

> Also, Fog Option to reduce/remove fog in water/lava and in the nether

I'll consider this.
- Water: I can def add a density slider.
- Nether: this has been asked before, I'll see what I can do without breaking vanilla stuff.
- Lava: not sure yet, really should just make screen black/white instead of fog imo

I probably won't be adding any ore lights though, past the option now for full iron/emerald/redstone/etc blocks
